# Generated by Django 4.1.2 on 2022-10-18 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paginas.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('nome_pai', models.CharField(max_length=255)),
                ('nome_mae', models.CharField(max_length=255)),
                ('contato_pai', models.CharField(blank=True, max_length=255)),
                ('contato_mae', models.CharField(max_length=255)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paginas.turma')),
            ],
        ),
    ]
