# Generated by Django 4.1.2 on 2022-10-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='mostrar',
            field=models.BooleanField(default=True),
        ),
    ]
